project:
  type: website
  output-dir: _site
  preview:
    port: 7777

pagetitle: "victorouse.zip / {{< zip_title >}}"

website:
  title: Victor Roussekov
  description: Data Engineer at Spaceship. Currently living in Sydney, Australia.
  favicon: images/favicon.ico

  google-analytics:
    tracking-id: G-R2S188R1KW
    version: 4
    anonymize-ip: false

  open-graph:
    description: Blog and resume

  twitter-card: 
    title: Victor Roussekov
    description: Blog and resume
    creator: "@victorouse"
    site: "@victorouse"

  page-navigation: true
  back-to-top-navigation: true
  repo-actions: [issue]


  site-url: https://victorouse.zip
  repo-url: https://github.com/victorouse/victorouse.github.io

  bread-crumbs: true

  search:
    show-item-context: true
    type: overlay

  page-footer:
    right:
      - icon: twitter
        href: https://twitter.com/victorouse
        aria-label: Twitter
      - icon: github
        href: https://github.com/victorouse
        aria-label: GitHub
      - icon: rss
        href: index.xml
        aria-label: RSS

  navbar:
    background: light
    title: false
    collapse-below: lg
    tools:
      - icon: github
        href: https://github.com/victorouse
        text: Github

      - icon: linkedin
        href: https://linkedin.com/in/victorouse
        text: LinkedIn

      - icon: twitter
        href: https://twitter.com/victorouse
        text: Twitter

      - icon: rss
        href: index.xml
        text: RSS

  sidebar:
    - id: main-nav
      collapse-level: 1
      contents:
        - text: Home
          href: index.qmd

        - text: Resume
          href: resume

        - section: Blog
          href: blog/index.qmd
          contents: blog/**/*

  comments:
    giscus:
      repo: victorouse/victorouse.github.io
      repo-id: R_kgDOKUMOAg
      category: Announcements
      category-id: DIC_kwDOKUMOAs4CZYOO
      mapping: title
      reactions-enabled: true
      loading: lazy
      input-position: top
      theme: light

format:
  html:
    toc: true
    link-external-icon: true
    link-external-newwindow: true

    code-copy: true
    code-overflow: wrap
    code-block-background: true

    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

    theme:
      light: [cosmo, styles.scss]

    filters:
      - social-share
    share:
      permalink: "https://victorouse.zip"
      description: "I'm with stoopid 👉"
      twitter: true
      reddit: true
      linkedin: true
      email: true
      mastodon: true

execute:
  freeze: true
