project:
  type: website
  output-dir: docs

website:
  title: "Victor Roussekov"
  open-graph: true
  twitter-card: 
    site: "@sitehandle"

  page-navigation: true
  back-to-top-navigation: true
  repo-actions: [issue]

  site-url: https://victorouse.github.io
  repo-url: https://github.com/victorouse/victorouse.github.io

  navbar:
    right:
      - icon: rss
        href: index.xml

  sidebar:
    logo: images/me.png
    align: center
    style: "floating"
    search: true

    tools:
      - icon: github
        href: https://github.com/victorouse
        text: "Github"

      - icon: linkedin
        href: https://linkedin.com/victorouse
        text: "LinkedIn"

      - icon: twitter
        href: https://twitter.com/victorouse
        text: "Twitter"

    contents:
      - text: "Home"
        file: index.qmd

      - section: "Posts"
        contents: posts/*

format:
  html:
    theme:
      light: cosmo
    code-background: true
    code-copy: true
    toc: true

execute:
  freeze: true
