project:
  type: website
  output-dir: _site
  preview:
    port: 7777

website:
  title: Victor Roussekov
  description: Blog and resume

  google-analytics: G-R2S188R1KW

  open-graph:
    description: Blog and resume

  twitter-card: 
    title: Victor Roussekov
    description: Blog and resume
    creator: "@victorouse"
    site: "@victorouse"

  page-navigation: true
  back-to-top-navigation: true
  repo-actions: [issue]

  site-url: https://victorouse.github.io
  repo-url: https://github.com/victorouse/victorouse.github.io

  bread-crumbs: true

  search:
    show-item-context: true
    type: overlay

  page-footer:
    right:
      - icon: twitter
        href: https://twitter.com/victorouse
        aria-label: Twitter
      - icon: github
        href: https://github.com/victorouse
        aria-label: GitHub
      - icon: rss
        href: index.xml
        aria-label: RSS

  navbar:
    background: light
    title: false
    collapse-below: lg
    tools:
      - icon: twitter
        href: https://twitter.com/victorouse
        text: Twitter
      - icon: github
        href: https://github.com/victorouse
        text: GitHub
      - icon: rss
        href: index.xml
        text: RSS

  sidebar:
    - id: posts
      collapse-level: 1
      contents:
        - text: "Home"
          href: index.qmd
        - section: "Blog"
          contents: blog/*

  comments:
    giscus:
      repo: victorouse/victorouse.github.io
      repo-id: R_kgDOKUMOAg
      category: Announcements
      category-id: DIC_kwDOKUMOAs4CZYOO
      mapping: title
      reactions-enabled: true
      loading: lazy
      input-position: top
      theme: light

format:
  html:
    toc: true
    theme:
      light: [cosmo, styles.scss]
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

execute:
  freeze: true
