project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Victor Roussekov"
  site-url: https://victorouse.github.io
  repo-url: https://github.com/victorouse/victorouse.github.io

  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/victorouse
        text: "Github"

    contents:
      - section: "Posts"
        contents:
          - index.qmd
          - first.qmd

format:
  html:
    theme:
      light: cosmo
    code-background: true
    code-copy: true
    toc: true

execute:
  freeze: true
